import { RNG } from '../rng';

/**
 * Test vectors below were generated by actually running the Go splitmix64
 * algorithm from pkg/gamecore/rng.go via `go run` (GOTOOLCHAIN=local) in the
 * CodeClash-be repo. rng_test.go itself pins no explicit expected values
 * (it only asserts determinism/range properties), so these numbers are the
 * source of truth for exact-value parity with the Go implementation.
 */
describe('RNG', () => {
  describe('splitmix64 exact vectors', () => {
    it('matches the Go implementation for seed=1', () => {
      const rng = new RNG(1);
      const expected = [
        10451216379200822465n,
        13757245211066428519n,
        17911839290282890590n,
        8196980753821780235n,
        8195237237126968761n,
        14072917602864530048n,
        16184226688143867045n,
        9648886400068060533n,
        5266705631892356520n,
        14646652180046636950n,
        7455107161863376737n,
        11168034603498703870n,
        8392123148533390784n,
        9778231605760336522n,
        8042142155559163816n,
        3081251696030599739n,
        11904322950028659555n,
        15040563541741120241n,
        12575237177726700014n,
        16312908901713405192n,
      ];
      const actual = expected.map(() => rng.next());
      expect(actual).toEqual(expected);
    });

    it('matches the Go implementation for seed=42', () => {
      const rng = new RNG(42);
      const expected = [
        13679457532755275413n,
        2949826092126892291n,
        5139283748462763858n,
        6349198060258255764n,
        701532786141963250n,
        16015981125662989062n,
        4028864712777624925n,
        14769051326987775908n,
        6270620877612482005n,
        11408980392250668974n,
        3779771651426294207n,
        9094045341461139646n,
        9470486766231111398n,
        9592552252706221495n,
        12270025419241524956n,
        3752715396868486130n,
        1910607418205583989n,
        9140336935745592861n,
        1723436047706647047n,
        12708817412199463008n,
      ];
      const actual = expected.map(() => rng.next());
      expect(actual).toEqual(expected);
    });

    it('matches the Go implementation for seed=1000001', () => {
      const rng = new RNG(1000001);
      const expected = [
        14734046666460977855n,
        1885096790310385968n,
        4738052383452540895n,
        4559030074013242595n,
        17605497565771302314n,
        14617394999827029227n,
        3705118747669331233n,
        17316949937553275956n,
        2062346959238577780n,
        15334041085548027176n,
        5534147244018909825n,
        6031694013689637221n,
        3928948389482841413n,
        18358007416896931218n,
        14037171965466041422n,
        8020235066923067391n,
        11607282599739010549n,
        3848461221439391786n,
        10227965206829214050n,
        15138212980984168569n,
      ];
      const actual = expected.map(() => rng.next());
      expect(actual).toEqual(expected);
    });

    it('matches the Go implementation for intN(6) with seed=999', () => {
      const rng = new RNG(999);
      const expected = [4, 4, 4, 3, 2, 5, 5, 5, 1, 2];
      const actual = expected.map(() => rng.intN(6));
      expect(actual).toEqual(expected);
    });
  });

  describe('property tests (ported from rng_test.go)', () => {
    it('produces identical sequences for the same seed', () => {
      const a = new RNG(12345);
      const b = new RNG(12345);
      for (let i = 0; i < 1000; i++) {
        expect(a.next()).toBe(b.next());
      }
    });

    it('diverges for different seeds within 8 draws', () => {
      const a = new RNG(1);
      const b = new RNG(2);
      let diverged = false;
      for (let i = 0; i < 8; i++) {
        if (a.next() !== b.next()) {
          diverged = true;
          break;
        }
      }
      expect(diverged).toBe(true);
    });

    it('intN stays in range and is deterministic for same seed', () => {
      const ns = [1, 2, 6, 100, 7];
      for (const n of ns) {
        const a = new RNG(999);
        const b = new RNG(999);
        for (let i = 0; i < 500; i++) {
          const va = a.intN(n);
          const vb = b.intN(n);
          expect(va).toBe(vb);
          expect(va).toBeGreaterThanOrEqual(0);
          expect(va).toBeLessThan(n);
        }
      }
    });

    it('throws on non-positive n', () => {
      const rng = new RNG(1);
      expect(() => rng.intN(0)).toThrow();
      expect(() => rng.intN(-1)).toThrow();
    });
  });
});
